language: php

php:
    - 5.4
    - 5.5
    - 5.6
    - hhvm
    - 7.0

matrix:
    fast_finish: true
    allow_failures:
        - php: 7.0
        - php: hhvm

before_install:
    - /home/travis/.phpenv/versions/$(phpenv version-name)/bin/composer self-update
    - sh -c "sudo mkdir vendor"
    - sh -c "sudo mount -t tmpfs -o size=512M tmpfs vendor"

install:
    - composer install --prefer-source --no-interaction

before_script:
    - sh -c "echo 'extension = redis.so' >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini"
    - sh -c "sudo mkdir /tmp/Bamboo"
    - sh -c "sudo mount -t tmpfs -o size=512M tmpfs /tmp/Bamboo/"

services:
    - redis-server

script:
    - bin/behat
    - bin/phpunit -c app

notifications:
    email: false

