services:

    #
    # Services
    #
    elcodi.store.geo.guzzle_client:
       class: %elcodi.store.geo.guzzle_client.class%

    elcodi.store.geo.services.geo_api_consumer:
        class: %elcodi.store.geo.services.geo_api_consumer.class%
        arguments:
            guzzle_client: @elcodi.store.geo.guzzle_client
            simple_geo_api_url: %simple_geo_api_url%

    elcodi.store.geo.form.city_selector_builder:
        class: %elcodi.store.geo.form.city_selector_builder.class%
        arguments:
            geo_api_consumer: @elcodi.store.geo.services.geo_api_consumer