services:

    #
    # Annotation resolver
    #
    elcodi.configuration.annotation_resolver:
        class: Elcodi\Common\ConfigurationBundle\Resolver\ConfigurationResolver
        arguments:
            - @elcodi.manager.configuration
        tags:
            - { name: controller_extra.annotation }
